# Generated by Django 4.2.7 on 2025-08-02 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ny', models.CharField(blank=True, max_length=100, verbose_name='Name (Chichewa)')),
                ('crop_type', models.CharField(choices=[('cereal', 'Cereals'), ('legume', 'Legumes'), ('tuber', 'Tubers'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('cash', 'Cash Crops')], max_length=20, verbose_name='Crop Type')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='Scientific Name')),
                ('planting_season', models.CharField(max_length=100, verbose_name='Planting Season')),
                ('harvest_season', models.CharField(max_length=100, verbose_name='Harvest Season')),
                ('water_requirement', models.CharField(max_length=50, verbose_name='Water Requirement')),
                ('soil_type', models.TextField(verbose_name='Suitable Soil Types')),
                ('growing_period_days', models.IntegerField(verbose_name='Growing Period (days)')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
            },
        ),
        migrations.CreateModel(
            name='MalawiRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='District Name')),
                ('region', models.CharField(choices=[('northern', 'Northern Region'), ('central', 'Central Region'), ('southern', 'Southern Region')], max_length=20, verbose_name='Region')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='Altitude (meters)')),
                ('annual_rainfall', models.IntegerField(blank=True, null=True, verbose_name='Annual Rainfall (mm)')),
            ],
            options={
                'verbose_name': 'Malawi District',
                'verbose_name_plural': 'Malawi Districts',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.FloatField(verbose_name='Max Temperature (°C)')),
                ('temperature_min', models.FloatField(verbose_name='Min Temperature (°C)')),
                ('humidity', models.FloatField(verbose_name='Humidity (%)')),
                ('rainfall', models.FloatField(default=0, verbose_name='Rainfall (mm)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind Speed (km/h)')),
                ('weather_condition', models.CharField(max_length=50, verbose_name='Weather Condition')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.malawiregion')),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-date'],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per KG (MWK)')),
                ('market_name', models.CharField(max_length=100, verbose_name='Market Name')),
                ('source', models.CharField(default='Manual Entry', max_length=100, verbose_name='Price Source')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.malawiregion')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('farm_size_acres', models.FloatField(verbose_name='Farm Size (acres)')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=2, verbose_name='Preferred Language')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.malawiregion', verbose_name='Location')),
                ('primary_crops', models.ManyToManyField(blank=True, to='advisory.crop', verbose_name='Primary Crops')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='CropAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('planting', 'Planting Advice'), ('care', 'Care & Maintenance'), ('disease', 'Disease Management'), ('harvest', 'Harvest Advice'), ('weather', 'Weather-based Advice'), ('general', 'General Advice')], max_length=20, verbose_name='Advice Type')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_ny', models.CharField(blank=True, max_length=200, verbose_name='Title (Chichewa)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_ny', models.TextField(blank=True, verbose_name='Content (Chichewa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('validity_days', models.IntegerField(default=7, verbose_name='Validity (days)')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.farmer')),
                ('weather_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.weatherdata')),
            ],
            options={
                'verbose_name': 'Crop Advice',
                'verbose_name_plural': 'Crop Advice',
                'ordering': ['-created_at', '-is_urgent'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='suitable_regions',
            field=models.ManyToManyField(to='advisory.malawiregion', verbose_name='Suitable Regions'),
        ),
        migrations.CreateModel(
            name='FarmingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('activity_en', models.CharField(max_length=200, verbose_name='Activity (English)')),
                ('activity_ny', models.CharField(blank=True, max_length=200, verbose_name='Activity (Chichewa)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ny', models.TextField(blank=True, verbose_name='Description (Chichewa)')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.crop')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.malawiregion')),
            ],
            options={
                'verbose_name': 'Farming Calendar Entry',
                'verbose_name_plural': 'Farming Calendar Entries',
                'ordering': ['month'],
                'unique_together': {('crop', 'region', 'month')},
            },
        ),
    ]
